### ISSUE TITLE
Showing content of IAGA-2002 not working on Achim's PC (UBUNTU Linux)

### ISSUE THREAD

**Issue by sputnik-a** [INTERMAGNET/DataCheck1s#6]
There is a memory error when trying to view IAGA-2002 files in text form:

java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:150)
	at java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:178)
	at sun.awt.image.SunVolatileImage.getBackupImage(SunVolatileImage.java:240)
	at sun.awt.image.VolatileSurfaceManager.getBackupSurface(VolatileSurfaceManager.java:263)
	at sun.awt.image.VolatileSurfaceManager.initialize(VolatileSurfaceManager.java:126)
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:92)
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:102)
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:113)
	at sun.awt.image.SunVolatileImage.<init>(SunVolatileImage.java:107)
	at sun.awt.X11.XComponentPeer.createVolatileImage(XComponentPeer.java:752)
	at java.awt.Component.createVolatileImage(Component.java:3608)
	at java.awt.Component$BltBufferStrategy.createBackBuffers(Component.java:4335)
	at java.awt.Component$BltBufferStrategy.<init>(Component.java:4280)
	at java.awt.Component$BltSubRegionBufferStrategy.<init>(Component.java:4533)
	at java.awt.Component.createBufferStrategy(Component.java:3859)
	at java.awt.Window.createBufferStrategy(Window.java:3357)
	at javax.swing.BufferStrategyPaintManager$BufferInfo.createBufferStrategy(BufferStrategyPaintManager.java:859)
	at javax.swing.BufferStrategyPaintManager$BufferInfo.createBufferStrategy(BufferStrategyPaintManager.java:810)
	at javax.swing.BufferStrategyPaintManager$BufferInfo.getBufferStrategy(BufferStrategyPaintManager.java:743)
	at javax.swing.BufferStrategyPaintManager.prepare(BufferStrategyPaintManager.java:520)
	at javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:276)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent.paint(JComponent.java:1042)
	at java.awt.GraphicsCallback$PaintCallback.run(GraphicsCallback.java:39)
	at sun.awt.SunGraphicsCallback.runOneComponent(SunGraphicsCallback.java:79)
	at sun.awt.SunGraphicsCallback.runComponents(SunGraphicsCallback.java:116)
	at java.awt.Container.paint(Container.java:1975)
	at java.awt.Window.paint(Window.java:3904)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:842)

**Comment by SimonFlower** [comment]
You can change the memory available to Java with the –Xmx option, for example “-Xmx1024m” to allocate 1Gb of memory to Java (I’m not sure what the default is on Linux). Can you experiment with this option to see whether it helps? You can set it in Netbeans through properties for the project, the ‘Run’ category and then add to the ‘VM Options’.
